[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
match_indent = true
pattern = '''G.deck:shuffle('cashout'..G.GAME.round_resets.ante)'''
position = "after"
payload = '''
for i=1, #G.jokers.cards do
    eval_card(G.jokers.cards[i], {pl_cash_out = true})
end
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.set == "Joker" and not self.debuff then'''
position = "after"
payload = '''
if self.ability.name == 'j_Plantain_inkblot_joker' and self.ability.extra.mimic then
    G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.15, func = function()
        self:flip()
        play_sound('tarot1')
        ;return true end }))
    G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.3, func = function()
        local old = self.config.center
        self:set_ability(self.ability.extra.mimic)
        self:flip()
        self.mimic = old
        ;return true end }))
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if context.individual then'''
position = "before"
payload = '''
if self.mimic and not context.individual and not context.repetition then
    G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.15, func = function()
        self:flip()
        play_sound('tarot1')
        ;return true end }))
    G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.3, func = function()
        self:set_ability(self.mimic)
        self:flip()
        ;return true end }))
    
end
'''
match_indent = true

