[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
match_indent = true
pattern = '''G.deck:shuffle('cashout'..G.GAME.round_resets.ante)'''
position = "after"
payload = '''
for i=1, #G.jokers.cards do
    eval_card(G.jokers.cards[i], {pl_cash_out = true})
end
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.set == "Joker" and not self.debuff then'''
position = "after"
payload = '''
if self.ability.name == 'j_Plantain_inkblot_joker' and self.ability.extra.mimic then
    local old = self.ability.extra.mimic
    G.GAME.plantain_inkbloats = {}
    G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.15, func = function()
        self:flip()
        play_sound('tarot1')
        G.E_MANAGER:add_event(Event({trigger = 'after', delay = 1, func = function()
            self:set_ability(old)
            self:flip()
            table.insert(G.GAME.plantain_inkbloats, old)
            ;return true end }))
        ;return true end }))
    
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if context.individual then'''
position = "before"
payload = '''
if not context.individual and not context.repetition and G.GAME.plantain_inkbloats then
    for k, v in pairs(G.GAME.plantain_inkbloats) do
        if v.key == self.config.center.key then
            table.remove(G.GAME.plantain_inkbloats, k)
            G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.15, func = function()
                self:flip()
                play_sound('tarot1')
                G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.3, func = function()
                    self:set_ability(G.P_CENTERS['j_Plantain_inkblot_joker'])
                    self:flip()
                    ;return true end }))
                ;return true end }))
        end
    end
end
'''
match_indent = true

