[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
match_indent = true
pattern = '''G.deck:shuffle('cashout'..G.GAME.round_resets.ante)'''
position = "after"
payload = '''
for i=1, #G.jokers.cards do
    eval_card(G.jokers.cards[i], {pl_cash_out = true})
end
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.set == "Joker" and not self.debuff then'''
position = "after"
payload = '''
if self.ability.name == 'j_Plantain_inkblot_joker' and self.ability.extra.mimic then
    local old = self.ability.extra.mimic
    self:set_ability(old)
    self.children.front = nil
    self.seal = 'Plantain_inkblot_joker_seal'
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if context.individual then'''
position = "before"
payload = '''
if not context.individual and not context.repetition then
    if self.seal == 'Plantain_inkblot_joker_seal' then
        self:set_ability(G.P_CENTERS['j_Plantain_inkblot_joker'])
        self.seal = nil
    end
end
'''
match_indent = true

