[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
match_indent = true
pattern = '''G.deck:shuffle('cashout'..G.GAME.round_resets.ante)'''
position = "after"
payload = '''
for i=1, #G.jokers.cards do
    eval_card(G.jokers.cards[i], {pl_cash_out = true})
end
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.set == "Joker" and not self.debuff then'''
position = "after"
payload = '''
if context.setting_blind and not self.getting_sliced and context.blind == G.GAME.round_resets.blind and self.config.center.key == 'j_Plantain_inkblot_joker' then
    if G.jokers then
        local options = {}
        for k, v in pairs(G.P_CENTERS) do
          if v.unlocked and v.set == 'Joker' and v.name ~= 'j_Plantain_inkblot_joker' and v.name ~= 'Shortcut' then
            if not v.mod then
                table.insert(options, v)
            end
          end
        end
        local chosen_key = pseudorandom_element(options, pseudoseed('inkblot_joker'..G.GAME.round_resets.ante))
        self:set_ability(chosen_key)
        self.mimic = G.P_CENTERS[chosen_key.key]
        self:set_sprites(G.P_CENTERS['j_Plantain_inkblot_joker'])
        self.config.center = G.P_CENTERS['j_Plantain_inkblot_joker']
    end
end
'''
match_indent = true
